spring.datasource.url=jdbc:postgresql://dpg-d7f55kvaqgkc73a1qcug-a/quizdb_yo1z
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Optional: show SQL in console
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.web=DEBUG
server.port=8080
server.address=0.0.0.0
spring.jpa.open-in-view=false